//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.18444
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrintSharpServer.DistantPrinter {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="DistantPrinter.PrinterSoap")]
    public interface PrinterSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Ping", ReplyAction="*")]
        bool Ping();
        
        // CODEGEN : La génération du contrat de message depuis le nom d'élément nom de l'espace de noms http://tempuri.org/ n'est pas marqué nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Print", ReplyAction="*")]
        PrintSharpServer.DistantPrinter.PrintResponse Print(PrintSharpServer.DistantPrinter.PrintRequest request);
        
        // CODEGEN : La génération du contrat de message depuis le nom d'élément StatusResult de l'espace de noms http://tempuri.org/ n'est pas marqué nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Status", ReplyAction="*")]
        PrintSharpServer.DistantPrinter.StatusResponse Status(PrintSharpServer.DistantPrinter.StatusRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PrintRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Print", Namespace="http://tempuri.org/", Order=0)]
        public PrintSharpServer.DistantPrinter.PrintRequestBody Body;
        
        public PrintRequest() {
        }
        
        public PrintRequest(PrintSharpServer.DistantPrinter.PrintRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class PrintRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int taille;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string nom;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int copies;
        
        public PrintRequestBody() {
        }
        
        public PrintRequestBody(int taille, string nom, int copies) {
            this.taille = taille;
            this.nom = nom;
            this.copies = copies;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PrintResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PrintResponse", Namespace="http://tempuri.org/", Order=0)]
        public PrintSharpServer.DistantPrinter.PrintResponseBody Body;
        
        public PrintResponse() {
        }
        
        public PrintResponse(PrintSharpServer.DistantPrinter.PrintResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class PrintResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int PrintResult;
        
        public PrintResponseBody() {
        }
        
        public PrintResponseBody(int PrintResult) {
            this.PrintResult = PrintResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class StatusRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Status", Namespace="http://tempuri.org/", Order=0)]
        public PrintSharpServer.DistantPrinter.StatusRequestBody Body;
        
        public StatusRequest() {
        }
        
        public StatusRequest(PrintSharpServer.DistantPrinter.StatusRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class StatusRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int jobId;
        
        public StatusRequestBody() {
        }
        
        public StatusRequestBody(int jobId) {
            this.jobId = jobId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class StatusResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="StatusResponse", Namespace="http://tempuri.org/", Order=0)]
        public PrintSharpServer.DistantPrinter.StatusResponseBody Body;
        
        public StatusResponse() {
        }
        
        public StatusResponse(PrintSharpServer.DistantPrinter.StatusResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class StatusResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string StatusResult;
        
        public StatusResponseBody() {
        }
        
        public StatusResponseBody(string StatusResult) {
            this.StatusResult = StatusResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface PrinterSoapChannel : PrintSharpServer.DistantPrinter.PrinterSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PrinterSoapClient : System.ServiceModel.ClientBase<PrintSharpServer.DistantPrinter.PrinterSoap>, PrintSharpServer.DistantPrinter.PrinterSoap {
        
        public PrinterSoapClient() {
        }
        
        public PrinterSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PrinterSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PrinterSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PrinterSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool Ping() {
            return base.Channel.Ping();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PrintSharpServer.DistantPrinter.PrintResponse PrintSharpServer.DistantPrinter.PrinterSoap.Print(PrintSharpServer.DistantPrinter.PrintRequest request) {
            return base.Channel.Print(request);
        }
        
        public int Print(int taille, string nom, int copies) {
            PrintSharpServer.DistantPrinter.PrintRequest inValue = new PrintSharpServer.DistantPrinter.PrintRequest();
            inValue.Body = new PrintSharpServer.DistantPrinter.PrintRequestBody();
            inValue.Body.taille = taille;
            inValue.Body.nom = nom;
            inValue.Body.copies = copies;
            PrintSharpServer.DistantPrinter.PrintResponse retVal = ((PrintSharpServer.DistantPrinter.PrinterSoap)(this)).Print(inValue);
            return retVal.Body.PrintResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PrintSharpServer.DistantPrinter.StatusResponse PrintSharpServer.DistantPrinter.PrinterSoap.Status(PrintSharpServer.DistantPrinter.StatusRequest request) {
            return base.Channel.Status(request);
        }
        
        public string Status(int jobId) {
            PrintSharpServer.DistantPrinter.StatusRequest inValue = new PrintSharpServer.DistantPrinter.StatusRequest();
            inValue.Body = new PrintSharpServer.DistantPrinter.StatusRequestBody();
            inValue.Body.jobId = jobId;
            PrintSharpServer.DistantPrinter.StatusResponse retVal = ((PrintSharpServer.DistantPrinter.PrinterSoap)(this)).Status(inValue);
            return retVal.Body.StatusResult;
        }
    }
}
