//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.18449
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrintSharpClient.DistantServer {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="DistantServer.ServerSoap")]
    public interface ServerSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Ping", ReplyAction="*")]
        bool Ping();
        
        // CODEGEN : La génération du contrat de message depuis le nom d'élément nom de l'espace de noms http://tempuri.org/ n'est pas marqué nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Print", ReplyAction="*")]
        PrintSharpClient.DistantServer.PrintResponse Print(PrintSharpClient.DistantServer.PrintRequest request);
        
        // CODEGEN : La génération du contrat de message depuis le nom d'élément StatusResult de l'espace de noms http://tempuri.org/ n'est pas marqué nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Status", ReplyAction="*")]
        PrintSharpClient.DistantServer.StatusResponse Status(PrintSharpClient.DistantServer.StatusRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PrintRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Print", Namespace="http://tempuri.org/", Order=0)]
        public PrintSharpClient.DistantServer.PrintRequestBody Body;
        
        public PrintRequest() {
        }
        
        public PrintRequest(PrintSharpClient.DistantServer.PrintRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class PrintRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int taille;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string nom;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int copies;
        
        public PrintRequestBody() {
        }
        
        public PrintRequestBody(int taille, string nom, int copies) {
            this.taille = taille;
            this.nom = nom;
            this.copies = copies;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PrintResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PrintResponse", Namespace="http://tempuri.org/", Order=0)]
        public PrintSharpClient.DistantServer.PrintResponseBody Body;
        
        public PrintResponse() {
        }
        
        public PrintResponse(PrintSharpClient.DistantServer.PrintResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class PrintResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int PrintResult;
        
        public PrintResponseBody() {
        }
        
        public PrintResponseBody(int PrintResult) {
            this.PrintResult = PrintResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class StatusRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Status", Namespace="http://tempuri.org/", Order=0)]
        public PrintSharpClient.DistantServer.StatusRequestBody Body;
        
        public StatusRequest() {
        }
        
        public StatusRequest(PrintSharpClient.DistantServer.StatusRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class StatusRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int jobId;
        
        public StatusRequestBody() {
        }
        
        public StatusRequestBody(int jobId) {
            this.jobId = jobId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class StatusResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="StatusResponse", Namespace="http://tempuri.org/", Order=0)]
        public PrintSharpClient.DistantServer.StatusResponseBody Body;
        
        public StatusResponse() {
        }
        
        public StatusResponse(PrintSharpClient.DistantServer.StatusResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class StatusResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string StatusResult;
        
        public StatusResponseBody() {
        }
        
        public StatusResponseBody(string StatusResult) {
            this.StatusResult = StatusResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServerSoapChannel : PrintSharpClient.DistantServer.ServerSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServerSoapClient : System.ServiceModel.ClientBase<PrintSharpClient.DistantServer.ServerSoap>, PrintSharpClient.DistantServer.ServerSoap {
        
        public ServerSoapClient() {
        }
        
        public ServerSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServerSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServerSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServerSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool Ping() {
            return base.Channel.Ping();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PrintSharpClient.DistantServer.PrintResponse PrintSharpClient.DistantServer.ServerSoap.Print(PrintSharpClient.DistantServer.PrintRequest request) {
            return base.Channel.Print(request);
        }
        
        public int Print(int taille, string nom, int copies) {
            PrintSharpClient.DistantServer.PrintRequest inValue = new PrintSharpClient.DistantServer.PrintRequest();
            inValue.Body = new PrintSharpClient.DistantServer.PrintRequestBody();
            inValue.Body.taille = taille;
            inValue.Body.nom = nom;
            inValue.Body.copies = copies;
            PrintSharpClient.DistantServer.PrintResponse retVal = ((PrintSharpClient.DistantServer.ServerSoap)(this)).Print(inValue);
            return retVal.Body.PrintResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PrintSharpClient.DistantServer.StatusResponse PrintSharpClient.DistantServer.ServerSoap.Status(PrintSharpClient.DistantServer.StatusRequest request) {
            return base.Channel.Status(request);
        }
        
        public string Status(int jobId) {
            PrintSharpClient.DistantServer.StatusRequest inValue = new PrintSharpClient.DistantServer.StatusRequest();
            inValue.Body = new PrintSharpClient.DistantServer.StatusRequestBody();
            inValue.Body.jobId = jobId;
            PrintSharpClient.DistantServer.StatusResponse retVal = ((PrintSharpClient.DistantServer.ServerSoap)(this)).Status(inValue);
            return retVal.Body.StatusResult;
        }
    }
}
